// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSecret(arg1, arg2) {
  return window['go']['main']['App']['AddSecret'](arg1, arg2);
}

export function GetActiveTasks() {
  return window['go']['main']['App']['GetActiveTasks']();
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function GetSecrets() {
  return window['go']['main']['App']['GetSecrets']();
}

export function RemoveSecret(arg1) {
  return window['go']['main']['App']['RemoveSecret'](arg1);
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SiphonCheckHTTP(arg1) {
  return window['go']['main']['App']['SiphonCheckHTTP'](arg1);
}

export function StartProcessing(arg1, arg2) {
  return window['go']['main']['App']['StartProcessing'](arg1, arg2);
}
