// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveTasks() {
  return window['go']['main']['App']['GetActiveTasks']();
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartProcessing(arg1) {
  return window['go']['main']['App']['StartProcessing'](arg1);
}
