// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sys} from '../models';
import {services} from '../models';
import {main} from '../models';

export function AddSecret(arg1:string,arg2:string):Promise<boolean>;

export function GetActiveTasks():Promise<Array<sys.Task>>;

export function GetMetrics():Promise<sys.MetricsDTO>;

export function GetSecrets():Promise<Array<services.Secret>>;

export function RemoveSecret(arg1:string):Promise<boolean>;

export function RunCommand(arg1:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function SiphonCheckHTTP(arg1:string):Promise<main.SiphonResult>;

export function StartProcessing(arg1:string,arg2:sys.ForgeSettings):Promise<number>;
