// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sys} from '../models';

export function GetActiveTasks():Promise<Array<sys.Task>>;

export function GetMetrics():Promise<sys.MetricsDTO>;

export function RunCommand(arg1:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function StartProcessing(arg1:string):Promise<number>;
